FROM golang:1.25-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    nginx \
    ca-certificates \
    curl \
    libnss3-tools \
    && rm -rf /var/lib/apt/lists/*

# Install mkcert
RUN curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64" \
    && chmod +x mkcert-v*-linux-amd64 \
    && mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert

# Install air for hot reload
RUN go install github.com/air-verse/air@latest

# Setup nginx
RUN rm -f /etc/nginx/sites-enabled/default
RUN mkdir -p /etc/ngate/certs /etc/nginx/sites-enabled /var/www/acme

# Redirect nginx logs to stdout/stderr
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# Init mkcert CA
RUN mkcert -install

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 80 443 8080

CMD ["sh", "-c", "nginx && sleep 1 && air -c .air.toml"]
